server:
  port: 8080

spring:
  application:
    name: threadly-api-gateway
  profiles:
    active: local
  cloud:
    gateway:
      enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - http://localhost:5173
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      default-filters:
        # Remove downstream CORS headers so only gateway-managed CORS is returned
        - RemoveResponseHeader=Access-Control-Allow-Origin
        - RemoveResponseHeader=Access-Control-Allow-Credentials
        # Dedupe just in case anything else adds CORS headers
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST
      routes:
        - id: threadly-user-authentication-service-public-routes
          uri: lb://threadly-user-authentication-service
          predicates:
            - Path=/api/v1/auth/**

        - id: threadly-user-authentication-service-private-routes
          uri: lb://threadly-user-authentication-service
          predicates:
            - Path=/api/v1/users/**

        - id: threadly-product-service-public-routes
          uri: lb://threadly-product-service
          predicates:
            - Path=/api/v1/products/**

        - id: threadly-product-service-private-admin-routes
          uri: lb://threadly-product-service
          predicates:
            - Path=/api/v1/admin/products/**
          filters:
            - RequireAdminRoleFilter
