server:
  port: 8080

spring:
  application:
    name: threadly-api-gateway
  profiles:
    active: local
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: threadly-user-authentication-service-public-routes
          uri: lb://threadly-user-authentication-service
          predicates:
            - Path=/api/v1/auth/**

        - id: threadly-user-authentication-service-private-routes
          uri: lb://threadly-user-authentication-service
          predicates:
            - Path=/api/v1/users/**

        - id: threadly-product-service-public-routes
          uri: lb://threadly-product-service
          predicates:
            - Path=/api/v1/products/**

        - id: threadly-product-service-private-admin-routes
          uri: lb://threadly-product-service
          predicates:
            - Path=/api/v1/admin/products/**
          filters:
            - RequireAdminRoleFilter